CREATE TABLE IF NOT EXISTS stores (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  address VARCHAR(255) DEFAULT '',
  latitude DOUBLE NULL,
  longitude DOUBLE NULL,
  checkin_radius INT DEFAULT 200,
  status VARCHAR(32) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS staff (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  gender VARCHAR(16) DEFAULT '',
  age INT NULL,
  id_card VARCHAR(32) DEFAULT '',
  role VARCHAR(64) DEFAULT '',
  position VARCHAR(64) DEFAULT '',
  phone VARCHAR(32) DEFAULT '',
  hire_date VARCHAR(32) DEFAULT '',
  max_per_week INT DEFAULT 6,
  status VARCHAR(32) DEFAULT 'active',
  invite_code VARCHAR(32) DEFAULT '',
  avatar_url VARCHAR(512) DEFAULT '',
  openid_bound TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS staff_store_memberships (
  staff_id VARCHAR(64) NOT NULL,
  store_id VARCHAR(64) NOT NULL,
  PRIMARY KEY (staff_id, store_id),
  CONSTRAINT fk_membership_staff FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE,
  CONSTRAINT fk_membership_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS staff_role_relations (
  id VARCHAR(64) PRIMARY KEY,
  staff_id VARCHAR(64) NOT NULL,
  store_id VARCHAR(64) DEFAULT '',
  phone VARCHAR(32) DEFAULT '',
  position VARCHAR(64) DEFAULT 'staff',
  position_text VARCHAR(64) DEFAULT '普通员工',
  role VARCHAR(64) NOT NULL DEFAULT 'employee',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_role_staff FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS shifts (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  time VARCHAR(64) DEFAULT '',
  need_count INT DEFAULT 1,
  color VARCHAR(32) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS schedules (
  store_id VARCHAR(64) NOT NULL,
  work_date VARCHAR(16) NOT NULL,
  shift_id VARCHAR(64) NOT NULL,
  staff_ids_json JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (store_id, work_date, shift_id),
  CONSTRAINT fk_schedule_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedule_shift FOREIGN KEY (shift_id) REFERENCES shifts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS attendance_records (
  id VARCHAR(96) PRIMARY KEY,
  work_date VARCHAR(16) NOT NULL,
  store_id VARCHAR(64) DEFAULT '',
  store_name VARCHAR(128) DEFAULT '',
  staff_id VARCHAR(64) NOT NULL,
  shift_id VARCHAR(64) NOT NULL,
  latitude DOUBLE NULL,
  longitude DOUBLE NULL,
  distance INT NULL,
  result VARCHAR(32) DEFAULT 'normal',
  clock_in VARCHAR(64) DEFAULT '',
  clock_out VARCHAR(64) DEFAULT '',
  out_latitude DOUBLE NULL,
  out_longitude DOUBLE NULL,
  out_distance INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS employee_bindings (
  id VARCHAR(96) PRIMARY KEY,
  staff_id VARCHAR(64) NOT NULL,
  openid VARCHAR(128) DEFAULT '',
  unionid VARCHAR(128) DEFAULT '',
  phone VARCHAR(32) DEFAULT '',
  nickname VARCHAR(128) DEFAULT '',
  avatar_url VARCHAR(512) DEFAULT '',
  role VARCHAR(64) DEFAULT 'employee',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_binding_staff FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
